# 📂 Dataset Overview

This dataset contains detailed information about startups that appeared on **US Shark Tank**, including season details, startup profiles, entrepreneurs, investment requests, deal outcomes, individual shark investments, and shark participation.

---

## 📺 Season & Episode Information
These features identify when and where each pitch took place.

- **Season Number**
- **Episode Number**
- **Pitch Number**
- **Season Start**
- **Season End**
- **Original Air Date**

---

## 🚀 Startup Information
These features describe the startup and its business.

- **Startup Name**
- **Industry**
- **Business Description**
- **Company Website**

---

## 👥 Entrepreneur Information
These features describe the founders presenting the startup.

- **Pitchers Gender**
- **Pitchers Average Age**
- **Pitchers City**
- **Pitchers State**
- **Entrepreneur Names**
- **Multiple Entrepreneurs**

---

## 💼 Business & Investment Request
These features summarize the startup's business metrics and funding request.

- **US Viewership**
- **Original Ask Amount**
- **Original Offered Equity**
- **Valuation Requested**

---

## 🤝 Deal Information
These features describe the final outcome of the pitch.

- **Got Deal**
- **Total Deal Amount**
- **Total Deal Equity**
- **Deal Valuation**
- **Number of Sharks in Deal**
- **Investment Amount Per Shark**
- **Equity Per Shark**
- **Royalty Deal**
- **Advisory Shares Equity**
- **Loan**
- **Deal Has Conditions**

---

## 🦈 Individual Shark Investments
These features record the investment amount and equity offered by each shark.

### Barbara Corcoran
- Barbara Corcoran Investment Amount
- Barbara Corcoran Investment Equity

### Mark Cuban
- Mark Cuban Investment Amount
- Mark Cuban Investment Equity

### Lori Greiner
- Lori Greiner Investment Amount
- Lori Greiner Investment Equity

### Robert Herjavec
- Robert Herjavec Investment Amount
- Robert Herjavec Investment Equity

### Daymond John
- Daymond John Investment Amount
- Daymond John Investment Equity

### Kevin O'Leary
- Kevin O'Leary Investment Amount
- Kevin O'Leary Investment Equity

### Guest Shark
- Guest Name
- Guest Investment Amount
- Guest Investment Equity

---

## 🪑 Shark Presence
These binary features indicate whether each shark was present during the pitch.

- **Barbara Corcoran Present**
- **Mark Cuban Present**
- **Lori Greiner Present**
- **Robert Herjavec Present**
- **Daymond John Present**
- **Kevin O'Leary Present**
- **Guest Present**

# Import Libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load Dataset

In [2]:
df = pd.read_csv("/kaggle/input/datasets/thirumani/shark-tank-us-dataset/Shark Tank US dataset.csv")

# Data Exploration

In [3]:
# Preview of
pd.set_option('display.max_columns', None)   # Implimenting this dataset to see all the columns
df.head(5)

,Season Number,Startup Name,Episode Number,Pitch Number,Season Start,Season End,Original Air Date,Industry,Business Description,Company Website,Pitchers Gender,Pitchers Average Age,Pitchers City,Pitchers State,Entrepreneur Names,Multiple Entrepreneurs,US Viewership,Original Ask Amount,Original Offered Equity,Valuation Requested,Got Deal,Total Deal Amount,Total Deal Equity,Deal Valuation,Number of Sharks in Deal,Investment Amount Per Shark,Equity Per Shark,Royalty Deal,Advisory Shares Equity,Loan,Deal Has Conditions,Barbara Corcoran Investment Amount,Barbara Corcoran Investment Equity,Mark Cuban Investment Amount,Mark Cuban Investment Equity,Lori Greiner Investment Amount,Lori Greiner Investment Equity,Robert Herjavec Investment Amount,Robert Herjavec Investment Equity,Daymond John Investment Amount,Daymond John Investment Equity,Kevin O Leary Investment Amount,Kevin O Leary Investment Equity,Guest Investment Amount,Guest Investment Equity,Guest Name,Barbara Corcoran Present,Mark Cuban Present,Lori Greiner Present,Robert Herjavec Present,Daymond John Present,Kevin O Leary Present,Guest Present
0,1,AvaTheElephant,1,1,9-Aug-09,5-Feb-10,9-Aug-09,Health/Wellness,Ava The Elephant - Baby and Child Care,http://www.avatheelephant.com/,Female,NaN,Atlanta,GA,Tiffany Krumins,0.0,4.15,50000.0,15.0,333333.0,1.0,50000.0,55.0,90909.0,1.0,50000.0,55.0,NaN,NaN,NaN,NaN,50000.0,55.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,1.0,1.0,1.0,NaN
1,1,MrTod'sPieFactory,1,2,9-Aug-09,5-Feb-10,9-Aug-09,Food and Beverage,Mr. Tod's Pie Factory - Specialty Food,http://whybake.com/,Male,NaN,Somerset,NJ,Tod Wilson,0.0,4.15,460000.0,10.0,4600000.0,1.0,460000.0,50.0,920000.0,2.0,230000.0,25.0,NaN,NaN,NaN,NaN,230000.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,230000.0,25.0,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,1.0,1.0,1.0,NaN
2,1,Wispots,1,3,9-Aug-09,5-Feb-10,9-Aug-09,Business Services,Wispots - Consumer Services,http://www.wispots.com/,Male,NaN,Cary,NC,Kevin Flannery,0.0,4.15,1200000.0,10.0,12000000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,1.0,1.0,1.0,NaN
3,1,CollegeFoxesPackingBoxes,1,4,9-Aug-09,5-Feb-10,9-Aug-09,Lifestyle/Home,College Foxes Packing Boxes - Consumer Services,http://collegehunkshaulingjunk.com/,Male,NaN,Tampa,FL,"Nick Friedman, Omar Soliman",0.0,4.15,250000.0,25.0,1000000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,1.0,1.0,1.0,NaN
4,1,IonicEar,1,5,9-Aug-09,5-Feb-10,9-Aug-09,Technology/Software,Ionic Ear - Novelties,NaN,Male,NaN,St. Paul,MN,Darrin Johnson,0.0,4.15,1000000.0,15.0,6666667.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,1.0,1.0,1.0,NaN

In [4]:
df.tail(5)

,Season Number,Startup Name,Episode Number,Pitch Number,Season Start,Season End,Original Air Date,Industry,Business Description,Company Website,Pitchers Gender,Pitchers Average Age,Pitchers City,Pitchers State,Entrepreneur Names,Multiple Entrepreneurs,US Viewership,Original Ask Amount,Original Offered Equity,Valuation Requested,Got Deal,Total Deal Amount,Total Deal Equity,Deal Valuation,Number of Sharks in Deal,Investment Amount Per Shark,Equity Per Shark,Royalty Deal,Advisory Shares Equity,Loan,Deal Has Conditions,Barbara Corcoran Investment Amount,Barbara Corcoran Investment Equity,Mark Cuban Investment Amount,Mark Cuban Investment Equity,Lori Greiner Investment Amount,Lori Greiner Investment Equity,Robert Herjavec Investment Amount,Robert Herjavec Investment Equity,Daymond John Investment Amount,Daymond John Investment Equity,Kevin O Leary Investment Amount,Kevin O Leary Investment Equity,Guest Investment Amount,Guest Investment Equity,Guest Name,Barbara Corcoran Present,Mark Cuban Present,Lori Greiner Present,Robert Herjavec Present,Daymond John Present,Kevin O Leary Present,Guest Present
1480,17,Street FC,10,1481,24-Sep-25,NaN,21-Jan-26,Technology/Software,app for hosting soccer pick-up games,https://streetfc.com/,Male,Middle,NaN,NaN,Kyle Martino,0.0,NaN,250000.0,2.5,10000000.0,1.0,250000.0,3.0,8333333.0,1.0,250000.0,3.0,NaN,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,250000.0,3.0,Alexis Ohanian,NaN,NaN,1.0,NaN,1.0,1.0,2.0
1481,17,BocceRoll,11,1482,24-Sep-25,NaN,28-Jan-26,Fitness/Sports/Outdoors,yard game,https://playbocceroll.com/,NaN,NaN,Madison,WI,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,1.0,2.0
1482,17,TheYesGirls,11,1483,24-Sep-25,NaN,28-Jan-26,Lifestyle/Home,Propasal planning,https://theyesgirls.com/,NaN,NaN,Orange County,CA,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,1.0,2.0
1483,17,BoxBlayde,11,1484,24-Sep-25,NaN,28-Jan-26,Electronics,Box cutter,https://www.boxblayde.com/,Male,Middle,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,1.0,2.0
1484,17,SOMNIA+,11,1485,24-Sep-25,NaN,28-Jan-26,Lifestyle/Home,Dorm beds,https://somniaplus.co/,Mixed Team,Middle,NaN,NaN,NaN,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,1.0,2.0

In [5]:
df.sample(4)

,Season Number,Startup Name,Episode Number,Pitch Number,Season Start,Season End,Original Air Date,Industry,Business Description,Company Website,Pitchers Gender,Pitchers Average Age,Pitchers City,Pitchers State,Entrepreneur Names,Multiple Entrepreneurs,US Viewership,Original Ask Amount,Original Offered Equity,Valuation Requested,Got Deal,Total Deal Amount,Total Deal Equity,Deal Valuation,Number of Sharks in Deal,Investment Amount Per Shark,Equity Per Shark,Royalty Deal,Advisory Shares Equity,Loan,Deal Has Conditions,Barbara Corcoran Investment Amount,Barbara Corcoran Investment Equity,Mark Cuban Investment Amount,Mark Cuban Investment Equity,Lori Greiner Investment Amount,Lori Greiner Investment Equity,Robert Herjavec Investment Amount,Robert Herjavec Investment Equity,Daymond John Investment Amount,Daymond John Investment Equity,Kevin O Leary Investment Amount,Kevin O Leary Investment Equity,Guest Investment Amount,Guest Investment Equity,Guest Name,Barbara Corcoran Present,Mark Cuban Present,Lori Greiner Present,Robert Herjavec Present,Daymond John Present,Kevin O Leary Present,Guest Present
1162,13,NoLimbits,18,1163,8-Oct-21,20-May-22,1-Apr-22,Fashion/Beauty,Adaptive clothing for people with disabilities,NaN,Female,Middle,NaN,NaN,Erica Cole,0.0,3.50,100000.0,6.0,1666667.0,1.0,100000.0,10.0,1000000.0,2.0,50000.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,50000.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50000.0,5.0,Emma Grede,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1483,17,BoxBlayde,11,1484,24-Sep-25,NaN,28-Jan-26,Electronics,Box cutter,https://www.boxblayde.com/,Male,Middle,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,NaN,1.0,NaN,NaN,1.0,2.0
852,10,SubSafe,13,853,7-Oct-18,12-May-19,27-Jan-19,Lifestyle/Home,SubSafe - sandwich container,NaN,Mixed Team,NaN,NaN,NaN,NaN,NaN,3.79,50000.0,13.0,384615.0,1.0,100000.0,25.0,400000.0,2.0,50000.0,12.5,NaN,NaN,NaN,NaN,NaN,NaN,50000.0,12.5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50000.0,12.5,Charles Barkley,0.0,1.0,1.0,1.0,0.0,1.0,NaN
724,9,Mirmir,5,725,1-Oct-17,25-Feb-18,22-Oct-17,Media/Entertainment,portable photo booth,NaN,Male,NaN,Los Angeles,CA,NaN,NaN,4.29,350000.0,10.0,3500000.0,1.0,700000.0,20.0,3500000.0,1.0,700000.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,700000.0,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,1.0,1.0,1.0,1.0,NaN

In [6]:
df.shape

(1485, 53)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1485 entries, 0 to 1484
Data columns (total 53 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Season Number                       1485 non-null   int64
 1   Startup Name                        1485 non-null   object
 2   Episode Number                      1485 non-null   int64
 3   Pitch Number                        1485 non-null   int64
 4   Season Start                        1485 non-null   object
 5   Season End                          1441 non-null   object
 6   Original Air Date                   1485 non-null   object
 7   Industry                            1485 non-null   object
 8   Business Description                1485 non-null   object
 9   Company Website                     961 non-null    object
 10  Pitchers Gender                     1476 non-null   object
 11  Pitchers Average Age                547 non-null    object
 12  Pitchers City                       818 non-null    object
 13  Pitchers State                      946 non-null    object
 14  Entrepreneur Names                  986 non-null    object
 15  Multiple Entrepreneurs              1056 non-null   float64
 16  US Viewership                       1473 non-null   float64
 17  Original Ask Amount                 1481 non-null   float64
 18  Original Offered Equity             1481 non-null   float64
 19  Valuation Requested                 1481 non-null   float64
 20  Got Deal                            1481 non-null   float64
 21  Total Deal Amount                   914 non-null    float64
 22  Total Deal Equity                   914 non-null    float64
 23  Deal Valuation                      914 non-null    float64
 24  Number of Sharks in Deal            914 non-null    float64
 25  Investment Amount Per Shark         914 non-null    float64
 26  Equity Per Shark                    914 non-null    float64
 27  Royalty Deal                        93 non-null     object
 28  Advisory Shares Equity              6 non-null      float64
 29  Loan                                60 non-null     float64
 30  Deal Has Conditions                 4 non-null      object
 31  Barbara Corcoran Investment Amount  146 non-null    float64
 32  Barbara Corcoran Investment Equity  146 non-null    float64
 33  Mark Cuban Investment Amount        263 non-null    float64
 34  Mark Cuban Investment Equity        263 non-null    float64
 35  Lori Greiner Investment Amount      240 non-null    float64
 36  Lori Greiner Investment Equity      240 non-null    float64
 37  Robert Herjavec Investment Amount   138 non-null    float64
 38  Robert Herjavec Investment Equity   138 non-null    float64
 39  Daymond John Investment Amount      126 non-null    float64
 40  Daymond John Investment Equity      126 non-null    float64
 41  Kevin O Leary Investment Amount     138 non-null    float64
 42  Kevin O Leary Investment Equity     138 non-null    float64
 43  Guest Investment Amount             153 non-null    float64
 44  Guest Investment Equity             153 non-null    float64
 45  Guest Name                          153 non-null    object
 46  Barbara Corcoran Present            1006 non-null   float64
 47  Mark Cuban Present                  1064 non-null   float64
 48  Lori Greiner Present                1112 non-null   float64
 49  Robert Herjavec Present             988 non-null    float64
 50  Daymond John Present                998 non-null    float64
 51  Kevin O Leary Present               1109 non-null   float64
 52  Guest Present                       147 non-null    float64
dtypes: float64(35), int64(3), object(15)
memory usage: 615.0+ KB

In [8]:
df.duplicated().sum()

# if it would have duplicates values
# Remove duplicate rows from the dataset code
# df.drop_duplicates(inplace=True)

np.int64(0)

In [9]:
df.isnull().sum()

Season Number                            0
Startup Name                             0
Episode Number                           0
Pitch Number                             0
Season Start                             0
Season End                              44
Original Air Date                        0
Industry                                 0
Business Description                     0
Company Website                        524
Pitchers Gender                          9
Pitchers Average Age                   938
Pitchers City                          667
Pitchers State                         539
Entrepreneur Names                     499
Multiple Entrepreneurs                 429
US Viewership                           12
Original Ask Amount                      4
Original Offered Equity                  4
Valuation Requested                      4
Got Deal                                 4
Total Deal Amount                      571
Total Deal Equity                      571
Deal Valuation                         571
Number of Sharks in Deal               571
Investment Amount Per Shark            571
Equity Per Shark                       571
Royalty Deal                          1392
Advisory Shares Equity                1479
Loan                                  1425
Deal Has Conditions                   1481
Barbara Corcoran Investment Amount    1339
Barbara Corcoran Investment Equity    1339
Mark Cuban Investment Amount          1222
Mark Cuban Investment Equity          1222
Lori Greiner Investment Amount        1245
Lori Greiner Investment Equity        1245
Robert Herjavec Investment Amount     1347
Robert Herjavec Investment Equity     1347
Daymond John Investment Amount        1359
Daymond John Investment Equity        1359
Kevin O Leary Investment Amount       1347
Kevin O Leary Investment Equity       1347
Guest Investment Amount               1332
Guest Investment Equity               1332
Guest Name                            1332
Barbara Corcoran Present               479
Mark Cuban Present                     421
Lori Greiner Present                   373
Robert Herjavec Present                497
Daymond John Present                   487
Kevin O Leary Present                  376
Guest Present                         1338
dtype: int64

In [10]:
df.nunique()

Season Number                           17
Startup Name                          1482
Episode Number                          29
Pitch Number                          1485
Season Start                            17
Season End                              16
Original Air Date                      359
Industry                                16
Business Description                  1482
Company Website                        959
Pitchers Gender                          3
Pitchers Average Age                     3
Pitchers City                          355
Pitchers State                          50
Entrepreneur Names                     981
Multiple Entrepreneurs                   2
US Viewership                          252
Original Ask Amount                     79
Original Offered Equity                 47
Valuation Requested                    180
Got Deal                                 2
Total Deal Amount                       71
Total Deal Equity                       64
Deal Valuation                         216
Number of Sharks in Deal                 5
Investment Amount Per Shark             81
Equity Per Shark                        74
Royalty Deal                             1
Advisory Shares Equity                   4
Loan                                    18
Deal Has Conditions                      1
Barbara Corcoran Investment Amount      30
Barbara Corcoran Investment Equity      29
Mark Cuban Investment Amount            47
Mark Cuban Investment Equity            41
Lori Greiner Investment Amount          46
Lori Greiner Investment Equity          47
Robert Herjavec Investment Amount       40
Robert Herjavec Investment Equity       36
Daymond John Investment Amount          33
Daymond John Investment Equity          36
Kevin O Leary Investment Amount         32
Kevin O Leary Investment Equity         34
Guest Investment Amount                 33
Guest Investment Equity                 33
Guest Name                              41
Barbara Corcoran Present                 2
Mark Cuban Present                       2
Lori Greiner Present                     2
Robert Herjavec Present                  2
Daymond John Present                     2
Kevin O Leary Present                    2
Guest Present                            2
dtype: int64

# Data Cleaning

In [11]:
# Drop rows where the target ('Got Deal') is missing, as supervised models require known target labels
df.dropna(subset=['Got Deal'], inplace=True)

In [12]:
# Remove irrelevant columns and columns with excessive missing values (>90%)
df.drop(['US Viewership','Startup Name','Company Website','Business Description','Entrepreneur Names','Original Air Date','Season Start','Season End','Pitchers City','Pitchers State','Guest Name','Advisory Shares Equity','Deal Has Conditions','Loan','Royalty Deal','Season Start','Season End','Original Air Date','Guest Name' ,'Guest Present','Royalty Deal','Advisory Shares Equity','Barbara Corcoran Investment Equity','Mark Cuban Investment Equity','Lori Greiner Investment Equity','Robert Herjavec Investment Equity','Daymond John Investment Equity','Kevin O Leary Investment Equity','Guest Investment Equity'],axis=1,inplace=True ) 
df.sample(5)

,Season Number,Episode Number,Pitch Number,Industry,Pitchers Gender,Pitchers Average Age,Multiple Entrepreneurs,Original Ask Amount,Original Offered Equity,Valuation Requested,Got Deal,Total Deal Amount,Total Deal Equity,Deal Valuation,Number of Sharks in Deal,Investment Amount Per Shark,Equity Per Shark,Barbara Corcoran Investment Amount,Mark Cuban Investment Amount,Lori Greiner Investment Amount,Robert Herjavec Investment Amount,Daymond John Investment Amount,Kevin O Leary Investment Amount,Guest Investment Amount,Barbara Corcoran Present,Mark Cuban Present,Lori Greiner Present,Robert Herjavec Present,Daymond John Present,Kevin O Leary Present
367,5,27,368,Fashion/Beauty,Male,NaN,0.0,500000.0,10.0,5000000.0,1.0,500000.0,15.00,3333333.0,1.0,500000.0,15.000,NaN,NaN,500000.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,0.0,1.0
684,8,19,685,Food and Beverage,Male,Middle,0.0,250000.0,10.0,2500000.0,1.0,250000.0,10.00,2500000.0,1.0,250000.0,10.000,NaN,NaN,250000.0,NaN,NaN,NaN,NaN,1.0,1.0,1.0,1.0,0.0,1.0
1114,13,6,1115,Lifestyle/Home,Male,Middle,0.0,300000.0,8.0,3750000.0,1.0,300000.0,33.33,900090.0,2.0,150000.0,16.665,NaN,NaN,150000.0,150000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1250,14,17,1251,Food and Beverage,Mixed Team,Middle,1.0,200000.0,10.0,2000000.0,1.0,200000.0,20.00,1000000.0,1.0,200000.0,20.000,200000.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
617,8,2,618,Food and Beverage,Male,NaN,NaN,1000000.0,10.0,10000000.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,1.0,1.0,1.0,1.0

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1481 entries, 0 to 1480
Data columns (total 30 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Season Number                       1481 non-null   int64
 1   Episode Number                      1481 non-null   int64
 2   Pitch Number                        1481 non-null   int64
 3   Industry                            1481 non-null   object
 4   Pitchers Gender                     1474 non-null   object
 5   Pitchers Average Age                545 non-null    object
 6   Multiple Entrepreneurs              1054 non-null   float64
 7   Original Ask Amount                 1481 non-null   float64
 8   Original Offered Equity             1481 non-null   float64
 9   Valuation Requested                 1481 non-null   float64
 10  Got Deal                            1481 non-null   float64
 11  Total Deal Amount                   914 non-null    float64
 12  Total Deal Equity                   914 non-null    float64
 13  Deal Valuation                      914 non-null    float64
 14  Number of Sharks in Deal            914 non-null    float64
 15  Investment Amount Per Shark         914 non-null    float64
 16  Equity Per Shark                    914 non-null    float64
 17  Barbara Corcoran Investment Amount  146 non-null    float64
 18  Mark Cuban Investment Amount        263 non-null    float64
 19  Lori Greiner Investment Amount      240 non-null    float64
 20  Robert Herjavec Investment Amount   138 non-null    float64
 21  Daymond John Investment Amount      126 non-null    float64
 22  Kevin O Leary Investment Amount     138 non-null    float64
 23  Guest Investment Amount             153 non-null    float64
 24  Barbara Corcoran Present            1002 non-null   float64
 25  Mark Cuban Present                  1064 non-null   float64
 26  Lori Greiner Present                1108 non-null   float64
 27  Robert Herjavec Present             988 non-null    float64
 28  Daymond John Present                998 non-null    float64
 29  Kevin O Leary Present               1105 non-null   float64
dtypes: float64(24), int64(3), object(3)
memory usage: 358.7+ KB

In [14]:
df.isnull().sum()

Season Number                            0
Episode Number                           0
Pitch Number                             0
Industry                                 0
Pitchers Gender                          7
Pitchers Average Age                   936
Multiple Entrepreneurs                 427
Original Ask Amount                      0
Original Offered Equity                  0
Valuation Requested                      0
Got Deal                                 0
Total Deal Amount                      567
Total Deal Equity                      567
Deal Valuation                         567
Number of Sharks in Deal               567
Investment Amount Per Shark            567
Equity Per Shark                       567
Barbara Corcoran Investment Amount    1335
Mark Cuban Investment Amount          1218
Lori Greiner Investment Amount        1241
Robert Herjavec Investment Amount     1343
Daymond John Investment Amount        1355
Kevin O Leary Investment Amount       1343
Guest Investment Amount               1328
Barbara Corcoran Present               479
Mark Cuban Present                     417
Lori Greiner Present                   373
Robert Herjavec Present                493
Daymond John Present                   483
Kevin O Leary Present                  376
dtype: int64

In [15]:
cols = [
    'Got Deal',
    'Total Deal Amount',
    'Total Deal Equity',
    'Deal Valuation',
    'Number of Sharks in Deal',
    'Investment Amount Per Shark',
    'Equity Per Shark',
    'Barbara Corcoran Investment Amount',
    'Mark Cuban Investment Amount',
    'Lori Greiner Investment Amount',
    'Robert Herjavec Investment Amount',
    'Daymond John Investment Amount',
    'Kevin O Leary Investment Amount',
    'Guest Investment Amount',
    'Barbara Corcoran Present',
    'Mark Cuban Present',
    'Lori Greiner Present',
    'Robert Herjavec Present',
    'Daymond John Present',
    'Kevin O Leary Present'
]

df[cols] = df[cols].fillna(0)

# Post - Cleaning Data Quality Check

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1481 entries, 0 to 1480
Data columns (total 30 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Season Number                       1481 non-null   int64
 1   Episode Number                      1481 non-null   int64
 2   Pitch Number                        1481 non-null   int64
 3   Industry                            1481 non-null   object
 4   Pitchers Gender                     1474 non-null   object
 5   Pitchers Average Age                545 non-null    object
 6   Multiple Entrepreneurs              1054 non-null   float64
 7   Original Ask Amount                 1481 non-null   float64
 8   Original Offered Equity             1481 non-null   float64
 9   Valuation Requested                 1481 non-null   float64
 10  Got Deal                            1481 non-null   float64
 11  Total Deal Amount                   1481 non-null   float64
 12  Total Deal Equity                   1481 non-null   float64
 13  Deal Valuation                      1481 non-null   float64
 14  Number of Sharks in Deal            1481 non-null   float64
 15  Investment Amount Per Shark         1481 non-null   float64
 16  Equity Per Shark                    1481 non-null   float64
 17  Barbara Corcoran Investment Amount  1481 non-null   float64
 18  Mark Cuban Investment Amount        1481 non-null   float64
 19  Lori Greiner Investment Amount      1481 non-null   float64
 20  Robert Herjavec Investment Amount   1481 non-null   float64
 21  Daymond John Investment Amount      1481 non-null   float64
 22  Kevin O Leary Investment Amount     1481 non-null   float64
 23  Guest Investment Amount             1481 non-null   float64
 24  Barbara Corcoran Present            1481 non-null   float64
 25  Mark Cuban Present                  1481 non-null   float64
 26  Lori Greiner Present                1481 non-null   float64
 27  Robert Herjavec Present             1481 non-null   float64
 28  Daymond John Present                1481 non-null   float64
 29  Kevin O Leary Present               1481 non-null   float64
dtypes: float64(24), int64(3), object(3)
memory usage: 358.7+ KB

In [17]:
df.isnull().sum()

Season Number                           0
Episode Number                          0
Pitch Number                            0
Industry                                0
Pitchers Gender                         7
Pitchers Average Age                  936
Multiple Entrepreneurs                427
Original Ask Amount                     0
Original Offered Equity                 0
Valuation Requested                     0
Got Deal                                0
Total Deal Amount                       0
Total Deal Equity                       0
Deal Valuation                          0
Number of Sharks in Deal                0
Investment Amount Per Shark             0
Equity Per Shark                        0
Barbara Corcoran Investment Amount      0
Mark Cuban Investment Amount            0
Lori Greiner Investment Amount          0
Robert Herjavec Investment Amount       0
Daymond John Investment Amount          0
Kevin O Leary Investment Amount         0
Guest Investment Amount                 0
Barbara Corcoran Present                0
Mark Cuban Present                      0
Lori Greiner Present                    0
Robert Herjavec Present                 0
Daymond John Present                    0
Kevin O Leary Present                   0
dtype: int64

In [18]:
df.nunique()

Season Number                           17
Episode Number                          29
Pitch Number                          1481
Industry                                16
Pitchers Gender                          3
Pitchers Average Age                     3
Multiple Entrepreneurs                   2
Original Ask Amount                     79
Original Offered Equity                 47
Valuation Requested                    180
Got Deal                                 2
Total Deal Amount                       72
Total Deal Equity                       64
Deal Valuation                         216
Number of Sharks in Deal                 6
Investment Amount Per Shark             82
Equity Per Shark                        74
Barbara Corcoran Investment Amount      31
Mark Cuban Investment Amount            48
Lori Greiner Investment Amount          47
Robert Herjavec Investment Amount       41
Daymond John Investment Amount          34
Kevin O Leary Investment Amount         33
Guest Investment Amount                 34
Barbara Corcoran Present                 2
Mark Cuban Present                       2
Lori Greiner Present                     2
Robert Herjavec Present                  2
Daymond John Present                     2
Kevin O Leary Present                    2
dtype: int64

# Statistical Summary

In [19]:
df.describe()

,Season Number,Episode Number,Pitch Number,Multiple Entrepreneurs,Original Ask Amount,Original Offered Equity,Valuation Requested,Got Deal,Total Deal Amount,Total Deal Equity,Deal Valuation,Number of Sharks in Deal,Investment Amount Per Shark,Equity Per Shark,Barbara Corcoran Investment Amount,Mark Cuban Investment Amount,Lori Greiner Investment Amount,Robert Herjavec Investment Amount,Daymond John Investment Amount,Kevin O Leary Investment Amount,Guest Investment Amount,Barbara Corcoran Present,Mark Cuban Present,Lori Greiner Present,Robert Herjavec Present,Daymond John Present,Kevin O Leary Present
count,1481.000000,1481.000000,1481.000000,1054.000000,1.481000e+03,1481.000000,1.481000e+03,1481.000000,1.481000e+03,1481.000000,1.481000e+03,1481.000000,1.481000e+03,1481.000000,1481.000000,1.481000e+03,1.481000e+03,1.481000e+03,1.481000e+03,1.481000e+03,1.481000e+03,1481.000000,1481.000000,1481.000000,1481.000000,1481.000000,1481.000000
mean,9.017556,12.163403,741.000000,0.458254,2.821296e+05,13.098359,3.669953e+06,0.617151,1.784350e+05,14.352856,1.344947e+06,0.814990,1.497893e+05,12.142155,14870.582939,4.454490e+04,3.469649e+04,2.575501e+04,1.500720e+04,2.203297e+04,2.152780e+04,0.412559,0.659014,0.596894,0.591492,0.468602,0.719109
std,4.407728,7.345455,427.672188,0.498491,3.446770e+05,8.397064,5.789331e+06,0.486246,3.003601e+05,16.220253,3.046015e+06,0.800045,2.679299e+05,14.565051,57472.322791,1.482727e+05,1.123825e+05,1.739715e+05,9.558618e+04,1.106996e+05,9.022228e+04,0.492461,0.474201,0.490687,0.491724,0.499182,0.449586
min,1.000000,1.000000,1.000000,0.000000,1.000000e+04,1.000000,4.000000e+04,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,5.000000,6.000000,371.000000,0.000000,1.000000e+05,8.000000,7.500000e+05,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000e+00,0.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,9.000000,11.000000,741.000000,0.000000,2.000000e+05,10.000000,1.800000e+06,1.000000,1.000000e+05,10.000000,3.333330e+05,1.000000,7.500000e+04,10.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000
75%,13.000000,18.000000,1111.000000,1.000000,3.430000e+05,20.000000,4.000000e+06,1.000000,2.500000e+05,25.000000,1.250000e+06,1.000000,2.000000e+05,20.000000,0.000000,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
max,17.000000,29.000000,1481.000000,1.000000,5.000000e+06,100.000000,1.000000e+08,1.000000,5.000000e+06,100.000000,3.600000e+07,5.000000,5.000000e+06,100.000000,700000.000000,2.000000e+06,1.175000e+06,5.000000e+06,3.000000e+06,2.500000e+06,1.250000e+06,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [20]:
df.corr(numeric_only = True)

,Season Number,Episode Number,Pitch Number,Multiple Entrepreneurs,Original Ask Amount,Original Offered Equity,Valuation Requested,Got Deal,Total Deal Amount,Total Deal Equity,Deal Valuation,Number of Sharks in Deal,Investment Amount Per Shark,Equity Per Shark,Barbara Corcoran Investment Amount,Mark Cuban Investment Amount,Lori Greiner Investment Amount,Robert Herjavec Investment Amount,Daymond John Investment Amount,Kevin O Leary Investment Amount,Guest Investment Amount,Barbara Corcoran Present,Mark Cuban Present,Lori Greiner Present,Robert Herjavec Present,Daymond John Present,Kevin O Leary Present
Season Number,1.000000,-0.023817,0.996210,0.161255,0.032376,-0.416762,0.183819,0.177161,0.101843,-0.082441,0.152351,0.131980,0.099158,-0.066013,0.059918,0.020159,0.083668,-0.015315,-0.023076,0.031173,0.179261,-0.352284,-0.304884,0.033578,-0.634835,-0.467753,-0.440765
Episode Number,-0.023817,1.000000,0.032667,0.027324,0.074725,-0.026412,0.047813,-0.009714,0.035316,-0.038635,0.026131,-0.056824,0.062038,-0.010817,0.022565,0.029782,-0.014029,0.077659,-0.007956,0.002315,-0.072433,-0.031537,0.139378,0.084837,0.046366,-0.063648,-0.027831
Pitch Number,0.996210,0.032667,1.000000,0.161665,0.037130,-0.416647,0.189118,0.176078,0.104309,-0.081787,0.155167,0.127936,0.103140,-0.064877,0.064478,0.021064,0.081889,-0.011492,-0.021991,0.031481,0.176395,-0.350128,-0.325790,0.016430,-0.641285,-0.475320,-0.456685
Multiple Entrepreneurs,0.161255,0.027324,0.161665,1.000000,0.029346,-0.117922,0.031717,0.125467,0.097766,0.007828,0.095035,0.101809,0.100092,0.003584,0.043149,0.054326,0.052718,0.033714,-0.033199,0.040233,0.042162,-0.075712,-0.059626,-0.001904,-0.134658,-0.127043,-0.123715
Original Ask Amount,0.032376,0.074725,0.037130,0.029346,1.000000,-0.135435,0.634177,-0.082092,0.485817,-0.147234,0.368026,-0.063894,0.489647,-0.139035,-0.027719,0.188204,0.161870,0.391128,-0.006261,0.219478,0.107215,-0.028522,0.017373,-0.005296,-0.055329,-0.008486,-0.026306
Original Offered Equity,-0.416762,-0.026412,-0.416647,-0.117922,-0.135435,1.000000,-0.412664,-0.112165,-0.149685,0.241691,-0.282175,-0.098698,-0.135539,0.235546,-0.010655,-0.093595,-0.127590,0.034159,-0.014792,-0.082080,-0.128272,0.171729,0.065817,-0.071429,0.284412,0.221145,0.186157
Valuation Requested,0.183819,0.047813,0.189118,0.031717,0.634177,-0.412664,1.000000,-0.037577,0.348732,-0.219912,0.555814,-0.034131,0.335292,-0.208040,-0.048152,0.198210,0.225772,0.111832,-0.023373,0.192256,0.157905,-0.101950,-0.072724,-0.024366,-0.167544,-0.126684,-0.137054
Got Deal,0.177161,-0.009714,0.176078,0.125467,-0.082092,-0.112165,-0.037577,1.000000,0.468061,0.697181,0.347887,0.802607,0.440479,0.656824,0.203861,0.236702,0.243250,0.116640,0.123700,0.156817,0.187997,-0.051013,-0.053740,0.035226,-0.117626,-0.095488,-0.081181
Total Deal Amount,0.101843,0.035316,0.104309,0.097766,0.485817,-0.149685,0.348732,0.468061,1.000000,0.273198,0.662959,0.417848,0.946378,0.248923,0.091159,0.479584,0.398207,0.534322,0.261983,0.339551,0.262390,-0.070334,-0.011989,0.029527,-0.078009,-0.055273,-0.068209
Total Deal Equity,-0.082441,-0.038635,-0.081787,0.007828,-0.147234,0.241691,-0.219912,0.697181,0.273198,1.000000,-0.029734,0.598386,0.254431,0.927858,0.163143,0.126713,0.071090,0.101776,0.218760,0.023582,0.051842,0.049053,-0.029524,-0.028043,0.062604,0.055712,0.040352
Deal Valuation,0.152351,0.026131,0.155167,0.095035,0.368026,-0.282175,0.555814,0.347887,0.662959,-0.029734,1.000000,0.275338,0.624034,-0.027597,0.018402,0.347660,0.470328,0.165520,0.018839,0.401217,0.206741,-0.063889,-0.043629,0.011174,-0.141915,-0.133642,-0.113679
Number of Sharks in Deal,0.131980,-0.056824,0.127936,0.101809,-0.063894,-0.098698,-0.034131,0.802607,0.417848,0.598386,0.275338,1.000000,0.262986,0.381335,0.159200,0.211918,0.250956,0.086941,0.095426,0.140500,0.187654,-0.030798,-0.036386,0.028483,-0.099498,-0.061927,-0.045017
Investment Amount Per Shark,0.099158,0.062038,0.103140,0.100092,0.489647,-0.135539,0.335292,0.440479,0.946378,0.254431,0.624034,0.262986,1.000000,0.296071,0.082034,0.435312,0.286736,0.580737,0.277725,0.318197,0.221318,-0.067612,-0.015644,0.024442,-0.075603,-0.061053,-0.077068
Equity Per Shark,-0.066013,-0.010817,-0.064877,0.003584,-0.139035,0.235546,-0.208040,0.656824,0.248923,0.927858,-0.027597,0.381335,0.296071,1.000000,0.156658,0.109587,0.043060,0.106034,0.237262,0.010797,0.026092,0.030814,-0.023617,-0.015427,0.061705,0.053417,0.033322
Barbara Corcoran Investment Amount,0.059918,0.022565,0.064478,0.043149,-0.027719,-0.010655,-0.048152,0.203861,0.091159,0.163143,0.018402,0.159200,0.082034,0.156658,1.000000,-0.027472,-0.077257,-0.031715,-0.030269,-0.041378,-0.048156,0.146220,-0.048726,-0.047554,-0.076368,-0.091738,-0.035991
Mark Cuban Investment Amount,0.020159,0.029782,0.021064,0.054326,0.188204,-0.093595,0.198210,0.236702,0.479584,0.126713,0.347660,0.211918,0.435312,0.109587,-0.027472,1.000000,0.091703,-0.018730,-0.029547,-0.047366,-0.018020,-0.004359,0.030487,-0.005914,-0.043106,-0.034941,-0.044213
Lori Greiner Investment Amount,0.083668,-0.014029,0.081889,0.052718,0.161870,-0.127590,0.225772,0.243250,0.398207,0.071090,0.470328,0.250956,0.286736,0.043060,-0.077257,0.091703,1.000000,-0.027965,-0.031865,0.036216,0.021814,-0.070367,0.001628,0.067335,-0.044811,-0.061623,-0.051079
Robert Herjavec Investment Amount,-0.015315,0.077659,-0.011492,0.033714,0.391128,0.034159,0.111832,0.116640,0.534322,0.101776,0.165520,0.086941,0.580737,0.106034,-0.031715,-0.018730,-0.027965,1.000000,-0.014655,-0.013601,-0.031406,-0.032496,0.017176,0.024351,0.049781,0.008351,0.006565
Daymond John Investment Amount,-0.023076,-0.007956,-0.021991,-0.033199,-0.006261,-0.014792,-0.023373,0.123700,0.261983,0.218760,0.018839,0.095426,0.277725,0.237262,-0.030269,-0.029547,-0.031865,-0.014655,1.000000,-0.013673,-0.034714,-0.054192,0.011818,0.008060,0.035846,0.110876,0.029043
Kevin O Leary Investment Amount,0.031173,0.002315,0.031481,0.040233,0.219478,-0.082080,0.192256,0.156817,0.339551,0.023582,0.401217,0.140500,0.318197,0.010797,-0.041378,-0.047366,0.036216,-0.013601,-0.013673,1.000000,0.003243,-0.030692,-0.015961,-0.004049,-0.031302,-0.030263,-0.013725
Guest Investment Amount,0.179261,-0.072433,0.176395,0.042162,0.107215,-0.128272,0.157905,0.187997,0.262390,0.051842,0.206741,0.187654,0.221318,0.026092,-0.048156,-0.018020,0.021814,-0.031406,-0.034714,0.003243,1.000000,-0.074746,-0.087063,0.003911,-0.179957,-0.087829,-0.094453
Barbara Corcoran Present,-0.352284,-0.031537,-0.350128,-0.075712,-0.028522,0.171729,-0.101950,-0.051013,-0.070334,0.049053,-0.063889,-0.030798,-0.067612,0.030814,0.146220,-0.004359,-0.070367,-0.032496,-0.054192,-0.030692,-0.074746,1.000000,0.272967,0.056756,0.342081,-0.036600,0.444414
Mark Cuban Present,-0.304884,0.139378,-0.325790,-0.059626,0.017373,0.065817,-0.072724,-0.053740,-0.011989,-0.029524,-0.043629,-0.036386,-0.015644,-0.023617,-0.048726,0.030487,0.001628,0.017176,0.011818,-0.015961,-0.087063,0.272967,1.000000,0.738826,0.549706,0.350078,0.726244
Lori Greiner Present,0.033578,0.084837,0.016430,-0.001904,-0.005296,-0.071429,-0.024366,0.035226,0.029527,-0.028043,0.011174,0.028483,0.024442,-0.015427,-0.047554,-0.005914,0.067335,0.024351,0.008060,-0.004049,0.003911,0.056756,0.738826,1.000000,0.381186,0.148285,0.625757
Robert Herjavec Present,-0.634835,0.046366,-0.641285,-0.134658,-0.055329,0.284412,-0.167544,-0.117626,-0.078009,0.062604,-0.141915,-0.099498,-0.075603,0.061705,-0.076368,-0.043106,-0.044811,0.049781,0.035846,-0.031302,-0.179957,0.342081,0.549706,0.381186,1.000000,0.364744,0.623682
Daymond John Present,-0.467753,-0.063648,-0.475320,-0.127043,-0.008486,0.221145,-0.126684,-0.095488,-0.055273,0.055712,-0.133642,-0.061927,-0.061053,0.053417,-0.091738,-0.034941,-0.061623,0.008351,0.110876,-0.030263,-0.087829,-0.036600,0.350078,0.148285,0.364744,1.000000,0.532708
Kevin O Leary Present,-0.440765,-0.027831,-0.456685,-0.123715,-0.026306,0.186157,-0.137054,-0.081181,-0.068209,0.040352,-0.113679,-0.045017,-0.077068,0.033322,-0.035991,-0.044213,-0.051079,0.006565,0.029043,-0.013725,-0.094453,0.444414,0.726244,0.625757,0.623682,0.532708,1.000000

#   Feature  Selection & Train-Test Split

In [21]:
#train columns
X = df.drop(["Got Deal"],axis = 1)
X.shape

(1481, 29)

In [22]:
# target column
y = df["Got Deal"]
y.shape

(1481,)

In [23]:
from sklearn.model_selection import train_test_split

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size = 0.2,random_state = 42)

In [24]:
X_train

,Season Number,Episode Number,Pitch Number,Industry,Pitchers Gender,Pitchers Average Age,Multiple Entrepreneurs,Original Ask Amount,Original Offered Equity,Valuation Requested,Total Deal Amount,Total Deal Equity,Deal Valuation,Number of Sharks in Deal,Investment Amount Per Shark,Equity Per Shark,Barbara Corcoran Investment Amount,Mark Cuban Investment Amount,Lori Greiner Investment Amount,Robert Herjavec Investment Amount,Daymond John Investment Amount,Kevin O Leary Investment Amount,Guest Investment Amount,Barbara Corcoran Present,Mark Cuban Present,Lori Greiner Present,Robert Herjavec Present,Daymond John Present,Kevin O Leary Present
381,6,1,382,Fashion/Beauty,Male,NaN,0.0,200000.0,20.0,1000000.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
532,7,10,533,Fashion/Beauty,Female,NaN,NaN,425000.0,10.0,4250000.0,425000.0,25.0,1700000.0,1.0,425000.0,25.00,0.0,0.0,0.0,425000.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0
755,9,13,756,Fashion/Beauty,Male,NaN,NaN,50000.0,20.0,250000.0,50000.0,20.0,250000.0,1.0,50000.0,20.00,50000.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0
482,6,26,483,Fashion/Beauty,Male,NaN,0.0,100000.0,10.0,1000000.0,200000.0,30.0,666667.0,2.0,100000.0,15.00,0.0,100000.0,0.0,0.0,100000.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
405,6,7,406,Children/Education,Male,NaN,1.0,1500000.0,5.0,30000000.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1130,13,10,1131,Media/Entertainment,Mixed Team,Middle,1.0,500000.0,5.0,10000000.0,500000.0,30.0,1666667.0,2.0,250000.0,15.00,0.0,250000.0,0.0,0.0,0.0,0.0,250000.0,0.0,0.0,0.0,0.0,0.0,0.0
1294,15,6,1295,Fitness/Sports/Outdoors,Male,Old,1.0,65000.0,10.0,650000.0,65000.0,33.3,195195.0,2.0,32500.0,16.65,0.0,0.0,32500.0,0.0,32500.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
860,10,15,861,Food and Beverage,Female,NaN,NaN,250000.0,10.0,2500000.0,400000.0,20.0,2000000.0,1.0,400000.0,20.00,0.0,0.0,0.0,0.0,0.0,0.0,400000.0,0.0,1.0,1.0,0.0,1.0,1.0
1459,17,5,1460,Food and Beverage,Female,Middle,0.0,200000.0,8.0,2500000.0,200000.0,20.0,1000000.0,1.0,200000.0,20.00,0.0,0.0,0.0,0.0,200000.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0
1126,13,9,1127,Lifestyle/Home,Male,Middle,0.0,200000.0,10.0,2000000.0,200000.0,30.0,666667.0,1.0,200000.0,30.00,0.0,0.0,0.0,0.0,200000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [25]:
X_test

,Season Number,Episode Number,Pitch Number,Industry,Pitchers Gender,Pitchers Average Age,Multiple Entrepreneurs,Original Ask Amount,Original Offered Equity,Valuation Requested,Total Deal Amount,Total Deal Equity,Deal Valuation,Number of Sharks in Deal,Investment Amount Per Shark,Equity Per Shark,Barbara Corcoran Investment Amount,Mark Cuban Investment Amount,Lori Greiner Investment Amount,Robert Herjavec Investment Amount,Daymond John Investment Amount,Kevin O Leary Investment Amount,Guest Investment Amount,Barbara Corcoran Present,Mark Cuban Present,Lori Greiner Present,Robert Herjavec Present,Daymond John Present,Kevin O Leary Present
123,3,6,124,Lifestyle/Home,Male,NaN,0.0,250000.0,25.0,1000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
432,6,14,433,Lifestyle/Home,Male,NaN,1.0,75000.0,15.0,500000.0,75000.0,33.0,227273.0,1.0,75000.0,33.0,0.0,0.0,75000.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0
1030,12,10,1031,Lifestyle/Home,Male,Middle,1.0,120000.0,20.0,600000.0,180000.0,30.0,600000.0,2.0,90000.0,15.0,0.0,90000.0,0.0,0.0,0.0,0.0,90000.0,0.0,0.0,0.0,0.0,0.0,0.0
529,7,9,530,Fashion/Beauty,Male,NaN,NaN,150000.0,15.0,1000000.0,150000.0,20.0,750000.0,2.0,75000.0,10.0,0.0,75000.0,75000.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
1414,16,14,1415,Fashion/Beauty,Male,Middle,0.0,1500000.0,5.0,30000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1098,13,2,1099,Fashion/Beauty,Mixed Team,Middle,1.0,375000.0,15.0,2500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1307,15,9,1308,Food and Beverage,Mixed Team,Middle,1.0,750000.0,5.0,15000000.0,750000.0,10.0,7500000.0,2.0,375000.0,5.0,0.0,375000.0,375000.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0
543,7,13,544,Lifestyle/Home,Male,NaN,NaN,100000.0,20.0,500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0
1469,17,8,1470,Lifestyle/Home,Male,Middle,0.0,150000.0,10.0,1500000.0,150000.0,12.0,1250000.0,1.0,150000.0,12.0,0.0,0.0,0.0,0.0,0.0,150000.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0
1010,12,5,1011,Food and Beverage,Male,Middle,0.0,750000.0,20.0,3750000.0,750000.0,40.0,1875000.0,4.0,187500.0,10.0,0.0,187500.0,187500.0,187500.0,0.0,0.0,187500.0,0.0,0.0,0.0,0.0,0.0,0.0

In [26]:
y_train

381     0.0
532     1.0
755     1.0
482     1.0
405     0.0
       ...
1130    1.0
1294    1.0
860     1.0
1459    1.0
1126    1.0
Name: Got Deal, Length: 1184, dtype: float64

In [27]:
y_test

123     0.0
432     1.0
1030    1.0
529     1.0
1414    0.0
       ...
1098    0.0
1307    1.0
543     0.0
1469    1.0
1010    1.0
Name: Got Deal, Length: 297, dtype: float64

# Handling Missing Values

In [28]:
#X_train.select_dtypes(include='number').skew()

In [29]:
 #nunique
#Pitchers Gender                          3
#Pitchers Average Age                     3
#Multiple Entrepreneurs                   2

In [30]:
from sklearn.impute import SimpleImputer

mode_imputer = SimpleImputer(strategy='most_frequent')

cols = [
    "Pitchers Gender",                     
    'Pitchers Average Age',                                   
    'Multiple Entrepreneurs'
    
]

mode_imputer.fit(X_train[cols])

X_train[cols] = mode_imputer.transform(X_train[cols])
X_test[cols] = mode_imputer.transform(X_test[cols])

In [31]:
X_train

,Season Number,Episode Number,Pitch Number,Industry,Pitchers Gender,Pitchers Average Age,Multiple Entrepreneurs,Original Ask Amount,Original Offered Equity,Valuation Requested,Total Deal Amount,Total Deal Equity,Deal Valuation,Number of Sharks in Deal,Investment Amount Per Shark,Equity Per Shark,Barbara Corcoran Investment Amount,Mark Cuban Investment Amount,Lori Greiner Investment Amount,Robert Herjavec Investment Amount,Daymond John Investment Amount,Kevin O Leary Investment Amount,Guest Investment Amount,Barbara Corcoran Present,Mark Cuban Present,Lori Greiner Present,Robert Herjavec Present,Daymond John Present,Kevin O Leary Present
381,6,1,382,Fashion/Beauty,Male,Middle,0.0,200000.0,20.0,1000000.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
532,7,10,533,Fashion/Beauty,Female,Middle,0.0,425000.0,10.0,4250000.0,425000.0,25.0,1700000.0,1.0,425000.0,25.00,0.0,0.0,0.0,425000.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0
755,9,13,756,Fashion/Beauty,Male,Middle,0.0,50000.0,20.0,250000.0,50000.0,20.0,250000.0,1.0,50000.0,20.00,50000.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0
482,6,26,483,Fashion/Beauty,Male,Middle,0.0,100000.0,10.0,1000000.0,200000.0,30.0,666667.0,2.0,100000.0,15.00,0.0,100000.0,0.0,0.0,100000.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
405,6,7,406,Children/Education,Male,Middle,1.0,1500000.0,5.0,30000000.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1130,13,10,1131,Media/Entertainment,Mixed Team,Middle,1.0,500000.0,5.0,10000000.0,500000.0,30.0,1666667.0,2.0,250000.0,15.00,0.0,250000.0,0.0,0.0,0.0,0.0,250000.0,0.0,0.0,0.0,0.0,0.0,0.0
1294,15,6,1295,Fitness/Sports/Outdoors,Male,Old,1.0,65000.0,10.0,650000.0,65000.0,33.3,195195.0,2.0,32500.0,16.65,0.0,0.0,32500.0,0.0,32500.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
860,10,15,861,Food and Beverage,Female,Middle,0.0,250000.0,10.0,2500000.0,400000.0,20.0,2000000.0,1.0,400000.0,20.00,0.0,0.0,0.0,0.0,0.0,0.0,400000.0,0.0,1.0,1.0,0.0,1.0,1.0
1459,17,5,1460,Food and Beverage,Female,Middle,0.0,200000.0,8.0,2500000.0,200000.0,20.0,1000000.0,1.0,200000.0,20.00,0.0,0.0,0.0,0.0,200000.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0
1126,13,9,1127,Lifestyle/Home,Male,Middle,0.0,200000.0,10.0,2000000.0,200000.0,30.0,666667.0,1.0,200000.0,30.00,0.0,0.0,0.0,0.0,200000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [32]:
X_test.isnull().sum()

Season Number                         0
Episode Number                        0
Pitch Number                          0
Industry                              0
Pitchers Gender                       0
Pitchers Average Age                  0
Multiple Entrepreneurs                0
Original Ask Amount                   0
Original Offered Equity               0
Valuation Requested                   0
Total Deal Amount                     0
Total Deal Equity                     0
Deal Valuation                        0
Number of Sharks in Deal              0
Investment Amount Per Shark           0
Equity Per Shark                      0
Barbara Corcoran Investment Amount    0
Mark Cuban Investment Amount          0
Lori Greiner Investment Amount        0
Robert Herjavec Investment Amount     0
Daymond John Investment Amount        0
Kevin O Leary Investment Amount       0
Guest Investment Amount               0
Barbara Corcoran Present              0
Mark Cuban Present                    0
Lori Greiner Present                  0
Robert Herjavec Present               0
Daymond John Present                  0
Kevin O Leary Present                 0
dtype: int64

# Encoding

In [33]:
print(X_train["Industry"].unique())
print(X_train['Pitchers Gender'].unique())
print(X_train['Pitchers Average Age'].unique())

['Fashion/Beauty' 'Children/Education' 'Lifestyle/Home'
 'Food and Beverage' 'Media/Entertainment' 'Health/Wellness'
 'Technology/Software' 'Business Services' 'Fitness/Sports/Outdoors'
 'Uncertain/Other' 'Pet Products' 'Electronics' 'Liquor/Alcohol'
 'Green/CleanTech' 'Travel' 'Automotive']
['Male' 'Female' 'Mixed Team']
['Middle' 'Old' 'Young']

In [34]:
# Ordinal encoding
from sklearn.preprocessing import OrdinalEncoder, OneHotEncoder

age_encoder = OrdinalEncoder(categories=[['Young', 'Middle', 'Old']])

age_encoder.fit(X_train[['Pitchers Average Age']])

# transform

X_train['encoded_Pitchers Average Age'] = age_encoder.transform(
    X_train[['Pitchers Average Age']]
).ravel()

X_test['encoded_Pitchers Average Age'] = age_encoder.transform(
    X_test[['Pitchers Average Age']]
).ravel()

X_test

,Season Number,Episode Number,Pitch Number,Industry,Pitchers Gender,Pitchers Average Age,Multiple Entrepreneurs,Original Ask Amount,Original Offered Equity,Valuation Requested,Total Deal Amount,Total Deal Equity,Deal Valuation,Number of Sharks in Deal,Investment Amount Per Shark,Equity Per Shark,Barbara Corcoran Investment Amount,Mark Cuban Investment Amount,Lori Greiner Investment Amount,Robert Herjavec Investment Amount,Daymond John Investment Amount,Kevin O Leary Investment Amount,Guest Investment Amount,Barbara Corcoran Present,Mark Cuban Present,Lori Greiner Present,Robert Herjavec Present,Daymond John Present,Kevin O Leary Present,encoded_Pitchers Average Age
123,3,6,124,Lifestyle/Home,Male,Middle,0.0,250000.0,25.0,1000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0
432,6,14,433,Lifestyle/Home,Male,Middle,1.0,75000.0,15.0,500000.0,75000.0,33.0,227273.0,1.0,75000.0,33.0,0.0,0.0,75000.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0
1030,12,10,1031,Lifestyle/Home,Male,Middle,1.0,120000.0,20.0,600000.0,180000.0,30.0,600000.0,2.0,90000.0,15.0,0.0,90000.0,0.0,0.0,0.0,0.0,90000.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
529,7,9,530,Fashion/Beauty,Male,Middle,0.0,150000.0,15.0,1000000.0,150000.0,20.0,750000.0,2.0,75000.0,10.0,0.0,75000.0,75000.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0
1414,16,14,1415,Fashion/Beauty,Male,Middle,0.0,1500000.0,5.0,30000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1098,13,2,1099,Fashion/Beauty,Mixed Team,Middle,1.0,375000.0,15.0,2500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1307,15,9,1308,Food and Beverage,Mixed Team,Middle,1.0,750000.0,5.0,15000000.0,750000.0,10.0,7500000.0,2.0,375000.0,5.0,0.0,375000.0,375000.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0
543,7,13,544,Lifestyle/Home,Male,Middle,0.0,100000.0,20.0,500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0
1469,17,8,1470,Lifestyle/Home,Male,Middle,0.0,150000.0,10.0,1500000.0,150000.0,12.0,1250000.0,1.0,150000.0,12.0,0.0,0.0,0.0,0.0,0.0,150000.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0
1010,12,5,1011,Food and Beverage,Male,Middle,0.0,750000.0,20.0,3750000.0,750000.0,40.0,1875000.0,4.0,187500.0,10.0,0.0,187500.0,187500.0,187500.0,0.0,0.0,187500.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [35]:
X_train

,Season Number,Episode Number,Pitch Number,Industry,Pitchers Gender,Pitchers Average Age,Multiple Entrepreneurs,Original Ask Amount,Original Offered Equity,Valuation Requested,Total Deal Amount,Total Deal Equity,Deal Valuation,Number of Sharks in Deal,Investment Amount Per Shark,Equity Per Shark,Barbara Corcoran Investment Amount,Mark Cuban Investment Amount,Lori Greiner Investment Amount,Robert Herjavec Investment Amount,Daymond John Investment Amount,Kevin O Leary Investment Amount,Guest Investment Amount,Barbara Corcoran Present,Mark Cuban Present,Lori Greiner Present,Robert Herjavec Present,Daymond John Present,Kevin O Leary Present,encoded_Pitchers Average Age
381,6,1,382,Fashion/Beauty,Male,Middle,0.0,200000.0,20.0,1000000.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0
532,7,10,533,Fashion/Beauty,Female,Middle,0.0,425000.0,10.0,4250000.0,425000.0,25.0,1700000.0,1.0,425000.0,25.00,0.0,0.0,0.0,425000.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0
755,9,13,756,Fashion/Beauty,Male,Middle,0.0,50000.0,20.0,250000.0,50000.0,20.0,250000.0,1.0,50000.0,20.00,50000.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0
482,6,26,483,Fashion/Beauty,Male,Middle,0.0,100000.0,10.0,1000000.0,200000.0,30.0,666667.0,2.0,100000.0,15.00,0.0,100000.0,0.0,0.0,100000.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0
405,6,7,406,Children/Education,Male,Middle,1.0,1500000.0,5.0,30000000.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1130,13,10,1131,Media/Entertainment,Mixed Team,Middle,1.0,500000.0,5.0,10000000.0,500000.0,30.0,1666667.0,2.0,250000.0,15.00,0.0,250000.0,0.0,0.0,0.0,0.0,250000.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
1294,15,6,1295,Fitness/Sports/Outdoors,Male,Old,1.0,65000.0,10.0,650000.0,65000.0,33.3,195195.0,2.0,32500.0,16.65,0.0,0.0,32500.0,0.0,32500.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,2.0
860,10,15,861,Food and Beverage,Female,Middle,0.0,250000.0,10.0,2500000.0,400000.0,20.0,2000000.0,1.0,400000.0,20.00,0.0,0.0,0.0,0.0,0.0,0.0,400000.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0
1459,17,5,1460,Food and Beverage,Female,Middle,0.0,200000.0,8.0,2500000.0,200000.0,20.0,1000000.0,1.0,200000.0,20.00,0.0,0.0,0.0,0.0,200000.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0
1126,13,9,1127,Lifestyle/Home,Male,Middle,0.0,200000.0,10.0,2000000.0,200000.0,30.0,666667.0,1.0,200000.0,30.00,0.0,0.0,0.0,0.0,200000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0

In [36]:

#One- hot - Encoding 

pitchers_gender_ohe = OneHotEncoder(sparse_output=False).set_output(transform='pandas')

pitchers_gender_ohe.fit(X_train[['Pitchers Gender']])

encoded_df = pitchers_gender_ohe.transform(X_train[['Pitchers Gender']])

X_train = pd.concat([X_train, encoded_df], axis=1)
X_train

,Season Number,Episode Number,Pitch Number,Industry,Pitchers Gender,Pitchers Average Age,Multiple Entrepreneurs,Original Ask Amount,Original Offered Equity,Valuation Requested,Total Deal Amount,Total Deal Equity,Deal Valuation,Number of Sharks in Deal,Investment Amount Per Shark,Equity Per Shark,Barbara Corcoran Investment Amount,Mark Cuban Investment Amount,Lori Greiner Investment Amount,Robert Herjavec Investment Amount,Daymond John Investment Amount,Kevin O Leary Investment Amount,Guest Investment Amount,Barbara Corcoran Present,Mark Cuban Present,Lori Greiner Present,Robert Herjavec Present,Daymond John Present,Kevin O Leary Present,encoded_Pitchers Average Age,Pitchers Gender_Female,Pitchers Gender_Male,Pitchers Gender_Mixed Team
381,6,1,382,Fashion/Beauty,Male,Middle,0.0,200000.0,20.0,1000000.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0
532,7,10,533,Fashion/Beauty,Female,Middle,0.0,425000.0,10.0,4250000.0,425000.0,25.0,1700000.0,1.0,425000.0,25.00,0.0,0.0,0.0,425000.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0
755,9,13,756,Fashion/Beauty,Male,Middle,0.0,50000.0,20.0,250000.0,50000.0,20.0,250000.0,1.0,50000.0,20.00,50000.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0
482,6,26,483,Fashion/Beauty,Male,Middle,0.0,100000.0,10.0,1000000.0,200000.0,30.0,666667.0,2.0,100000.0,15.00,0.0,100000.0,0.0,0.0,100000.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0
405,6,7,406,Children/Education,Male,Middle,1.0,1500000.0,5.0,30000000.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1130,13,10,1131,Media/Entertainment,Mixed Team,Middle,1.0,500000.0,5.0,10000000.0,500000.0,30.0,1666667.0,2.0,250000.0,15.00,0.0,250000.0,0.0,0.0,0.0,0.0,250000.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1294,15,6,1295,Fitness/Sports/Outdoors,Male,Old,1.0,65000.0,10.0,650000.0,65000.0,33.3,195195.0,2.0,32500.0,16.65,0.0,0.0,32500.0,0.0,32500.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,2.0,0.0,1.0,0.0
860,10,15,861,Food and Beverage,Female,Middle,0.0,250000.0,10.0,2500000.0,400000.0,20.0,2000000.0,1.0,400000.0,20.00,0.0,0.0,0.0,0.0,0.0,0.0,400000.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0
1459,17,5,1460,Food and Beverage,Female,Middle,0.0,200000.0,8.0,2500000.0,200000.0,20.0,1000000.0,1.0,200000.0,20.00,0.0,0.0,0.0,0.0,200000.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0
1126,13,9,1127,Lifestyle/Home,Male,Middle,0.0,200000.0,10.0,2000000.0,200000.0,30.0,666667.0,1.0,200000.0,30.00,0.0,0.0,0.0,0.0,200000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [37]:
X_train.drop(columns=['Pitchers Average Age', 'Pitchers Gender'], inplace=True)
X_test.drop(columns=['Pitchers Average Age', 'Pitchers Gender'], inplace=True)

In [38]:
X_train

,Season Number,Episode Number,Pitch Number,Industry,Multiple Entrepreneurs,Original Ask Amount,Original Offered Equity,Valuation Requested,Total Deal Amount,Total Deal Equity,Deal Valuation,Number of Sharks in Deal,Investment Amount Per Shark,Equity Per Shark,Barbara Corcoran Investment Amount,Mark Cuban Investment Amount,Lori Greiner Investment Amount,Robert Herjavec Investment Amount,Daymond John Investment Amount,Kevin O Leary Investment Amount,Guest Investment Amount,Barbara Corcoran Present,Mark Cuban Present,Lori Greiner Present,Robert Herjavec Present,Daymond John Present,Kevin O Leary Present,encoded_Pitchers Average Age,Pitchers Gender_Female,Pitchers Gender_Male,Pitchers Gender_Mixed Team
381,6,1,382,Fashion/Beauty,0.0,200000.0,20.0,1000000.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0
532,7,10,533,Fashion/Beauty,0.0,425000.0,10.0,4250000.0,425000.0,25.0,1700000.0,1.0,425000.0,25.00,0.0,0.0,0.0,425000.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0
755,9,13,756,Fashion/Beauty,0.0,50000.0,20.0,250000.0,50000.0,20.0,250000.0,1.0,50000.0,20.00,50000.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0
482,6,26,483,Fashion/Beauty,0.0,100000.0,10.0,1000000.0,200000.0,30.0,666667.0,2.0,100000.0,15.00,0.0,100000.0,0.0,0.0,100000.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0
405,6,7,406,Children/Education,1.0,1500000.0,5.0,30000000.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1130,13,10,1131,Media/Entertainment,1.0,500000.0,5.0,10000000.0,500000.0,30.0,1666667.0,2.0,250000.0,15.00,0.0,250000.0,0.0,0.0,0.0,0.0,250000.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0
1294,15,6,1295,Fitness/Sports/Outdoors,1.0,65000.0,10.0,650000.0,65000.0,33.3,195195.0,2.0,32500.0,16.65,0.0,0.0,32500.0,0.0,32500.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,2.0,0.0,1.0,0.0
860,10,15,861,Food and Beverage,0.0,250000.0,10.0,2500000.0,400000.0,20.0,2000000.0,1.0,400000.0,20.00,0.0,0.0,0.0,0.0,0.0,0.0,400000.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0
1459,17,5,1460,Food and Beverage,0.0,200000.0,8.0,2500000.0,200000.0,20.0,1000000.0,1.0,200000.0,20.00,0.0,0.0,0.0,0.0,200000.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0
1126,13,9,1127,Lifestyle/Home,0.0,200000.0,10.0,2000000.0,200000.0,30.0,666667.0,1.0,200000.0,30.00,0.0,0.0,0.0,0.0,200000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0

In [39]:
industry_ohe = OneHotEncoder(sparse_output=False).set_output(transform='pandas')

industry_ohe.fit(X_train[['Industry']])

encoded_df_train = industry_ohe.transform(X_train[['Industry']])
encoded_df_test = industry_ohe.transform(X_test[['Industry']])

X_train = pd.concat([X_train, encoded_df_train], axis=1)
X_test = pd.concat([X_test, encoded_df_test], axis=1)

X_train.drop(columns=['Industry'], inplace=True)
X_test.drop(columns=['Industry'], inplace=True)

In [40]:
X_train

,Season Number,Episode Number,Pitch Number,Multiple Entrepreneurs,Original Ask Amount,Original Offered Equity,Valuation Requested,Total Deal Amount,Total Deal Equity,Deal Valuation,Number of Sharks in Deal,Investment Amount Per Shark,Equity Per Shark,Barbara Corcoran Investment Amount,Mark Cuban Investment Amount,Lori Greiner Investment Amount,Robert Herjavec Investment Amount,Daymond John Investment Amount,Kevin O Leary Investment Amount,Guest Investment Amount,Barbara Corcoran Present,Mark Cuban Present,Lori Greiner Present,Robert Herjavec Present,Daymond John Present,Kevin O Leary Present,encoded_Pitchers Average Age,Pitchers Gender_Female,Pitchers Gender_Male,Pitchers Gender_Mixed Team,Industry_Automotive,Industry_Business Services,Industry_Children/Education,Industry_Electronics,Industry_Fashion/Beauty,Industry_Fitness/Sports/Outdoors,Industry_Food and Beverage,Industry_Green/CleanTech,Industry_Health/Wellness,Industry_Lifestyle/Home,Industry_Liquor/Alcohol,Industry_Media/Entertainment,Industry_Pet Products,Industry_Technology/Software,Industry_Travel,Industry_Uncertain/Other
381,6,1,382,0.0,200000.0,20.0,1000000.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
532,7,10,533,0.0,425000.0,10.0,4250000.0,425000.0,25.0,1700000.0,1.0,425000.0,25.00,0.0,0.0,0.0,425000.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
755,9,13,756,0.0,50000.0,20.0,250000.0,50000.0,20.0,250000.0,1.0,50000.0,20.00,50000.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
482,6,26,483,0.0,100000.0,10.0,1000000.0,200000.0,30.0,666667.0,2.0,100000.0,15.00,0.0,100000.0,0.0,0.0,100000.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
405,6,7,406,1.0,1500000.0,5.0,30000000.0,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1130,13,10,1131,1.0,500000.0,5.0,10000000.0,500000.0,30.0,1666667.0,2.0,250000.0,15.00,0.0,250000.0,0.0,0.0,0.0,0.0,250000.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
1294,15,6,1295,1.0,65000.0,10.0,650000.0,65000.0,33.3,195195.0,2.0,32500.0,16.65,0.0,0.0,32500.0,0.0,32500.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
860,10,15,861,0.0,250000.0,10.0,2500000.0,400000.0,20.0,2000000.0,1.0,400000.0,20.00,0.0,0.0,0.0,0.0,0.0,0.0,400000.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1459,17,5,1460,0.0,200000.0,8.0,2500000.0,200000.0,20.0,1000000.0,1.0,200000.0,20.00,0.0,0.0,0.0,0.0,200000.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1126,13,9,1127,0.0,200000.0,10.0,2000000.0,200000.0,30.0,666667.0,1.0,200000.0,30.00,0.0,0.0,0.0,0.0,200000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0

In [41]:
X_test

,Season Number,Episode Number,Pitch Number,Multiple Entrepreneurs,Original Ask Amount,Original Offered Equity,Valuation Requested,Total Deal Amount,Total Deal Equity,Deal Valuation,Number of Sharks in Deal,Investment Amount Per Shark,Equity Per Shark,Barbara Corcoran Investment Amount,Mark Cuban Investment Amount,Lori Greiner Investment Amount,Robert Herjavec Investment Amount,Daymond John Investment Amount,Kevin O Leary Investment Amount,Guest Investment Amount,Barbara Corcoran Present,Mark Cuban Present,Lori Greiner Present,Robert Herjavec Present,Daymond John Present,Kevin O Leary Present,encoded_Pitchers Average Age,Industry_Automotive,Industry_Business Services,Industry_Children/Education,Industry_Electronics,Industry_Fashion/Beauty,Industry_Fitness/Sports/Outdoors,Industry_Food and Beverage,Industry_Green/CleanTech,Industry_Health/Wellness,Industry_Lifestyle/Home,Industry_Liquor/Alcohol,Industry_Media/Entertainment,Industry_Pet Products,Industry_Technology/Software,Industry_Travel,Industry_Uncertain/Other
123,3,6,124,0.0,250000.0,25.0,1000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
432,6,14,433,1.0,75000.0,15.0,500000.0,75000.0,33.0,227273.0,1.0,75000.0,33.0,0.0,0.0,75000.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1030,12,10,1031,1.0,120000.0,20.0,600000.0,180000.0,30.0,600000.0,2.0,90000.0,15.0,0.0,90000.0,0.0,0.0,0.0,0.0,90000.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
529,7,9,530,0.0,150000.0,15.0,1000000.0,150000.0,20.0,750000.0,2.0,75000.0,10.0,0.0,75000.0,75000.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1414,16,14,1415,0.0,1500000.0,5.0,30000000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1098,13,2,1099,1.0,375000.0,15.0,2500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1307,15,9,1308,1.0,750000.0,5.0,15000000.0,750000.0,10.0,7500000.0,2.0,375000.0,5.0,0.0,375000.0,375000.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
543,7,13,544,0.0,100000.0,20.0,500000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1469,17,8,1470,0.0,150000.0,10.0,1500000.0,150000.0,12.0,1250000.0,1.0,150000.0,12.0,0.0,0.0,0.0,0.0,0.0,150000.0,0.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
1010,12,5,1011,0.0,750000.0,20.0,3750000.0,750000.0,40.0,1875000.0,4.0,187500.0,10.0,0.0,187500.0,187500.0,187500.0,0.0,0.0,187500.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0